Add "Contributing" to README.md
xix-xeaon/IT23-game pull request #1
Opened 2024-01-24 11:47 UTC by ExclusiveKnight

I have added "Contributing" to README.md because there will be forks of the main repository, and people who are not familiar with GitHub **will have a hard time** pushing their changes to the repository.
So this is a way to help begineers. :)

Suggestions on what more I could do to improve the "Contributing" section are welcome.

2024-01-26 10:27 UTC, ExclusiveKnight commented
I'm a bit of a noob when it comes to GitHub. I reverted the commit above this message so it doesn't get merged into the main repo.

2024-01-30 21:27 UTC, ExclusiveKnight commented
That is my **final commit**, I need feedback on the latest commit so this can finally be pushed to main.

2024-01-31 08:37 UTC, lawin666 approved these changes

2024-01-31 08:38 UTC, ExclusiveKnight commented
Ready to merge?

2024-02-01 09:25 UTC, xix-xeaon requested changes
We shouldn't depend on a patch version, make the requirement 4.2 and I think this can be merged.

2024-02-01 09:56 UTC, ExclusiveKnight commented
Will do.

2024-02-01 10:08 UTC, ExclusiveKnight commented on README.md
> +- [Godot Engine](https://godotengine.org/download/windows/)
Will fix that in my commit, don't worry about it lol

2024-02-01 10:17 UTC, ExclusiveKnight commented
Fixed.

2024-02-01 12:07 UTC, xix-xeaon approved these changes

2024-02-01 12:08 UTC, merged