Spawn monster to game_scene
xix-xeaon/IT23-game pull request #28
Opened 2024-03-07 12:29 UTC by ligamesh123

2024-03-07 13:44 UTC, ra1nns commented
Very nice keep in mind we have 2 mobs try to make it so both types of mobs can spawn instead of just one spawning in

2024-03-08 11:39 UTC, Tobeast1 commented
In full screen the mobs spawn in view of the player. Try changing the Mode and Aspect in Project>Project Settings>Display>Window.

2024-03-13 08:54 UTC, ExclusiveKnight requested changes

2024-03-13 08:54 UTC, ExclusiveKnight commented on game.tscn
> +rotation = -0.00174927
This PR works like it should, but PathFollow2D shouldn't be rotated. Reset it's rotation.

2024-03-13 13:58 UTC, DNQ4 commented
I think we should also make it so that the game keeps track of how many enimes there is? Or at least make the enemies slow in the beginning of the game, I do not know we if we are going to implement player leveling and new weapons upgrades during the game, but it could end up that the mobs overwhelm the player in the beginning of the game with their speed and spawn rate.

2024-03-13 14:05 UTC, ligamesh123 commented
Right now we have 2 options to spawn different monster:
1. We can spawn them same time in one function .
2. We can have a delay between different enemy spawn time.
Or if u guy have better option so we can do this.

2024-03-14 09:28 UTC, xix-xeaon commented
Closing in favor of #27

2024-03-14 09:28 UTC, closed without merging