Add tree obstacle
xix-xeaon/IT23-game pull request #3
Opened 2024-01-26 12:06 UTC by Tobeast1

2024-01-26 12:20 UTC, lawin666 requested changes
I think the collisionshape is a little bit too big. U can make it to a rectangle instead n make it as big as the tree trunk.

2024-01-31 13:55 UTC, daogiabaohp420 commented
I think you can put your collisionshape2D down only around the trunk of tree so it make the game more 2D when player stand behind the tree.

2024-02-01 09:35 UTC, xix-xeaon requested changes
This PR needs a bit of cleanup but otherwise I think it's fine and could be merged.

2024-02-01 09:35 UTC, xix-xeaon commented on README.md
This file shouldn't be removed.

2024-02-01 09:35 UTC, xix-xeaon commented on icon.svg
This file shouldn't be removed either.

2024-02-01 09:35 UTC, xix-xeaon commented on Trees/foliagePack_005.png.import
This change doesn't make sense, I think this commit is incorrect.

2024-02-01 09:35 UTC, xix-xeaon commented on Trees/pine_tree.tscn
> +[node name="StaticBody2D" type="StaticBody2D"]
The name "StaticBody2D" is going to make it confusing to use later on.

2024-02-02 11:56 UTC, xix-xeaon approved these changes
LGTM

2024-02-02 11:57 UTC, merged