Added a background and a path
xix-xeaon/IT23-game pull request #6
Opened 2024-02-02 11:44 UTC by lawin666

2024-02-07 08:43 UTC, Snurrigt1 commented
Change camera zoom to 0.8

2024-02-08 08:19 UTC, xix-xeaon requested changes
I believe there are some unnesseccary changes that probably shouldn't be included in this PR. But other than that I think this is acceptable. In a future PR someone should probably improve this to use tilemaps or similar to make it easier to work with.

2024-02-08 08:19 UTC, xix-xeaon commented on Player/player.tscn
Why are there changes to the player?

2024-02-12 08:59 UTC, xix-xeaon commented
I see what your intention is now. There are a few things I'm not happy with but I suppose we'll have to merge soon anyway and fix those things later.

However, the unrelated changes to the project file are still blocking this PR from being merged.

2024-02-15 13:30 UTC, xix-xeaon approved these changes

2024-02-15 13:30 UTC, merged