Add 'AudioManager' function + Main Menu
xix-xeaon/IT23-game pull request #7
Opened 2024-02-02 11:50 UTC by ExclusiveKnight

I have created a simple main menu screen for the game, along with an audio manager system to handle sounds in a much better and efficient way.
This pull request contains:
- AudioManager.gd (Set as Autoload in Project settings)
- Main menu + background music
- A Start Game button that makes sounds (it works but doesn't do anything else since there is no level(s) available yet)
- A Sounds folder containing a Music folder & UI (User Interface) folder

2024-02-02 12:05 UTC, xix-xeaon commented
I'm not sure if we need an AudioManager, it's not part of the minimum viable project plan. Update this code to include only the main menu. We might have use of an AudioManger in the future though.

2024-02-07 09:22 UTC, Snurrigt1 reviewed
Looks good for a main menu

2024-02-08 08:30 UTC, xix-xeaon requested changes
Just two small changes, then I think we can merge.

You do however need to learn to **make way fewer commits**, even 10 commits for this change would be too many and you're way past that.

2024-02-08 08:30 UTC, xix-xeaon commented on Menu/Main/main-menu.tscn
> +text = "Created By NTI Malmö"
This should include "IT23" somehow.

2024-02-08 12:51 UTC, ExclusiveKnight commented on project.godot
me and the others from my class agreed to make the main menu the main scene but okay

2024-02-12 09:03 UTC, xix-xeaon commented on project.godot
I was not aware of this. It seems you've updated the PR with this information now so it's okay to make it the main scene!

2024-02-12 09:10 UTC, ExclusiveKnight commented on project.godot
I'll re-add it when I have time because the main menu is no longer the project's main scene in my latest commit.

2024-02-14 09:39 UTC, xix-xeaon approved these changes

2024-02-14 09:41 UTC, merged