Health management
xix-xeaon/IT23-game pull request #8
Opened 2024-02-02 11:53 UTC by Snurrigt1

- Health management
- Health bar
- Enemy damage rate

2024-02-08 08:44 UTC, xix-xeaon requested changes
Please cleariy in the PR how you intend the damage/death system to work and the signal. Same thing about collision layers.

2024-02-08 08:44 UTC, xix-xeaon commented on Player/player.tscn
> +[sub_resource type="RectangleShape2D" id="RectangleShape2D_1arvl"]
I believe we'll need the collisionshape of the hurtbox to extend beyond the collisionshape of the character or it won't detect any enemies.

2024-02-08 08:44 UTC, xix-xeaon commented on Player/player.gd
> +	const DAMAGE_RATE = 5.0
Constants like this are usually put near the top of a file for easy access.

2024-02-08 08:44 UTC, xix-xeaon commented on Player/player.tscn
> +collision_mask = 2
If we're going to use collision layers then they'll need to be named or it will be difficult to keep track of them.

2024-02-08 13:11 UTC, Snurrigt1 commented
The use of the signal health depleted will be used to make the game over screen appear in the future (when the game over screen has been implemented).

2024-02-12 09:08 UTC, xix-xeaon commented on project.godot
> +2d_physics/layer_2="Player"
It looks like the player is actually on layer 1. Shouldn't layer 2 be for enemies? That's the layer being detected by the hurtbox.

2024-02-14 09:47 UTC, xix-xeaon approved these changes

2024-02-14 09:48 UTC, merged